#!/usr/bin/env python
"""Generate closed-form ground-truth fixtures for src/microstructure.rs.

Samples random Gaussian mixtures (orientation weights on random unit vertices +
three isotropic compartments), runs the dipy FORCE closed forms
(crash_force fork, `dipy.sims._force_moments`), and writes inputs + outputs as a
plain-text fixture consumed by `cargo test` (pure std parsing, no serde).

Run with the fork's env:
    python tools/gen_force_fixtures.py   # inside the crash_force dipy-fork env

Cases avoid near-degenerate mean-tensor eigenvalues (relative gaps >= 5%):
eigenvector-dependent scalars (AK, RTAP/RTPP axis, NGpar/NGperp) are unstable
there and the Rust port covers those regimes with analytic limit tests instead.
"""

import sys
from pathlib import Path

import numpy as np

from dipy.sims import _force_moments as fm

SEED = 20260813
N_CASES = 30
OUT = Path(__file__).resolve().parent.parent / "tests" / "fixtures" / "force_moments.txt"

TAU_DEFAULT = 1.0 / (4.0 * np.pi**2)


def sample_case(rng):
    K = int(rng.integers(6, 25))
    v = rng.normal(size=(K, 3))
    v /= np.linalg.norm(v, axis=1, keepdims=True)

    # fractions: wm split intra/extra + gm + csf + soma, summing to exactly 1
    raw = rng.dirichlet([4.0, 3.0, 1.5, 1.0, 0.5])  # wm_in, wm_ex, gm, csf, soma
    if rng.random() < 0.3:
        raw[4] = 0.0  # exercise the soma-off path
    if rng.random() < 0.2:
        raw[3] = 0.0  # and csf-off
    raw /= raw.sum()
    w_in, w_ex, gm_f, csf_f, soma_f = raw

    intra = rng.random(K) + 1e-3
    extra = rng.random(K) + 1e-3
    intra *= w_in / intra.sum()
    extra *= w_ex / extra.sum()

    d_par = rng.uniform(0.8e-3, 2.4e-3)
    d_perp = rng.uniform(0.5e-4, 0.6 * d_par)
    gm_d = rng.uniform(0.5e-3, 1.5e-3)
    csf_d = rng.uniform(2.5e-3, 3.2e-3)
    soma_d = rng.uniform(0.2e-3, 1.5e-3)
    tau = TAU_DEFAULT if rng.random() < 0.5 else rng.uniform(0.01, 0.05)
    return dict(
        verts=v, intra=intra, extra=extra,
        gm_f=gm_f, gm_d=gm_d, csf_f=csf_f, csf_d=csf_d,
        soma_f=soma_f, soma_d=soma_d,
        d_par=d_par, d_perp=d_perp, tau=tau,
    )


def eig_gaps_ok(D_app):
    ev = np.sort(np.linalg.eigvalsh(D_app[0]))[::-1]
    return (ev[0] - ev[1]) / ev[0] >= 0.05 and (ev[1] - ev[2]) / ev[0] >= 0.05


def fmt(x):
    return " ".join(repr(float(t)) for t in np.asarray(x, np.float64).ravel())


def main():
    rng = np.random.default_rng(SEED)
    lines = [
        f"# dipy FORCE closed-form fixtures — seed {SEED}, {N_CASES} cases",
        "# generated by tools/gen_force_fixtures.py; do not edit by hand",
    ]
    kept = 0
    while kept < N_CASES:
        c = sample_case(rng)
        common = dict(
            gm_frac=c["gm_f"], gm_d=c["gm_d"], csf_frac=c["csf_f"], csf_d=c["csf_d"],
            soma_frac=c["soma_f"], soma_d=c["soma_d"],
        )
        D_app, C = fm.moments_from_odfs(
            c["intra"], c["extra"], c["verts"], c["d_par"], c["d_perp"],
            intra_dperp=0.0, **common,
        )
        if not eig_gaps_ok(D_app):
            continue
        dki_params = fm.dki_params_from_moments(D_app, C)
        sc = fm.dki_scalars_from_params(dki_params)
        qti = fm.qti_indices_from_moments(D_app, C)
        mp = fm.mapmri_closed_form_indices(
            c["intra"], c["extra"], c["verts"], c["d_par"], c["d_perp"],
            tau=c["tau"], **common,
        )
        ng = fm.ng_pa_from_odfs(
            c["intra"], c["extra"], c["verts"], c["d_par"], c["d_perp"],
            top_k=999, **common,
        )
        wmf = c["intra"].sum() + c["extra"].sum()
        gqi = fm.gqi_indices_from_odfs(c["intra"] + c["extra"], wmf)

        K = len(c["verts"])
        lines += [
            f"case {kept}",
            f"nverts {K}",
            f"verts {fmt(c['verts'])}",
            f"intra {fmt(c['intra'])}",
            f"extra {fmt(c['extra'])}",
            f"iso {fmt([c['gm_f'], c['gm_d'], c['csf_f'], c['csf_d'], c['soma_f'], c['soma_d']])}",
            f"dpar {fmt(c['d_par'])}",
            f"dperp {fmt(c['d_perp'])}",
            f"tau {fmt(c['tau'])}",
            f"D_app {fmt(D_app)}",
            f"C {fmt(C)}",
            f"dki_params {fmt(dki_params)}",
            "scalars "
            + fmt([sc['fa'], sc['md'], sc['rd'], sc['ad'], sc['ak'], sc['rk'],
                   sc['mk'], sc['mkt'], sc['kfa']]),
            "qti " + fmt([qti['micro_fa'], qti['coherence'], qti['k_bulk'], qti['k_shear']]),
            "mapmri " + fmt([mp['rtop'], mp['rtap'], mp['rtpp'], mp['msd'], mp['qiv']]),
            "ngpa " + fmt([ng['ng'], ng['ngpar'], ng['ngperp'], ng['pa']]),
            "gqi " + fmt([gqi['gfa'], gqi['qa']]),
            "end",
        ]
        kept += 1

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT} ({kept} cases, {OUT.stat().st_size} bytes)")
    # sanity summary
    print("sample case 0 keys OK; e.g. fa,mk,micro_fa,rtop,ng,gfa all finite")


if __name__ == "__main__":
    sys.exit(main())
